### ISSUE TITLE
Inclusão de JavaScript

### ISSUE THREAD

**Issue by marcosdourado** [fabriicioa/estruturaDeDados#1]
Algum motivo para a não inclusão de JavaScript?

Fiquei na dúvida se a lista é uma limitação ou uma sugestão.

**Comment by fabricioandradesantos** [comment]
Olá boa noite!
As linguagens listadas no repositório são apenas uma sugestão mesmo.
Podemos expandir para outras com certeza!
Obs: Dado a sua pergunta irei modificar o README para incentivar a galera
disponibilizar em JavaScript também rs
--Espero que você possa contribuir também!

Em ter., 14 de jan. de 2020 às 20:40, Marcos Dourado <
notifications@github.com> escreveu:

**Comment by marcosdourado** [comment]
Certo, pretendo. Só preciso revisar os algoritmos, faz tempo que não tenho contato com eles.
Uma última sugestão é criar labels para organizar as issues (Não apareceram aqui pra mim).

**Comment by fabricioandradesantos** [comment]
Muito boa sua sugestão!
Ainda estou me acostumando com algumas funcionalidades do GitHub.
